### ISSUE TITLE
`--sarif` flag behavior differs from other tool flags when path doesn't exist

### ISSUE THREAD

**Issue by clavedeluna** [pixee/codemodder-python#609]
`codemodder tests/samples --output output.codetf --codemod-include=secure-random --sarif=bad.json --verbose`

fails with
```
loading registered SARIF tool detectors
Traceback (most recent call last):
  File "/Users/dani/propixee/bin/codemodder", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/dani/codemodder-python/src/codemodder/codemodder.py", line 244, in main
    sys.exit(run(sys_argv))
             ^^^^^^^^^^^^^
  File "/Users/dani/codemodder-python/src/codemodder/codemodder.py", line 161, in run
    tool_result_files_map: DefaultDict[str, list[str]] = detect_sarif_tools(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/dani/codemodder-python/src/codemodder/sarifs.py", line 26, in detect_sarif_tools
    data = json.loads(fname.read_text())
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1027, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'bad.json'
```

However, running `codemodder tests/samples --output output.codetf --codemod-include=secure-random --defectdojo-findings-json=bad.json --verbose` or `codemodder tests/samples --output output.codetf --codemod-include=secure-random --sonar-issues-json=bad.json --verbose` runs codemodder just fine, but that's equally confusing since it would indicate that some results were loaded. What behavior do we want here?

**Comment by drdavella** [comment]
@clavedeluna nice catch, I think to be consistent we should fail and exit for all of these cases. I think that provides the most predictable behavior.
